server:
  port: 8761

spring:
  application:
    name: eurekaserver  # <-- Corrige la indentación aquí

eureka:
  client:
    register-with-eureka: false  # <-- Corrige la indentación aquí
    fetch-registry: false  # <-- Corrige la indentación aquí
